### PR TITLE
long_description is a string

### PR DESCRIPTION
**Pull request by asottile**
This fixes wheel building in python3

### CODE REVIEW

**Comment by asottile** [comment]
### before

```
$ python3.6 -m pip wheel . --no-deps
Processing /private/tmp/flask-xsrf
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/flask_xsrf.egg-info
    writing pip-egg-info/flask_xsrf.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7x/97jnmnt13sl46bx2mc9chzpm0000gn/T/pip-7g041ns5-build/setup.py", line 56, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules'
      File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/local/lib/python3.6/site-packages/setuptools/dist.py", line 91, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
        lines = header.split('\n')
    AttributeError: 'list' object has no attribute 'split'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7x/97jnmnt13sl46bx2mc9chzpm0000gn/T/pip-7g041ns5-build/
```

### after

```
$ python3.6 -m pip wheel . --no-deps
Processing /private/tmp/flask-xsrf
Building wheels for collected packages: flask-xsrf
  Running setup.py bdist_wheel for flask-xsrf ... done
  Stored in directory: /private/tmp/flask-xsrf
Successfully built flask-xsrf
```

**Review by gregorynicholas — APPROVED** [review]

**Comment by asottile** [comment]
@gregorynicholas anything additional I need to do here?

**Comment by asottile** [comment]
Thanks!  Any chance you could make a 1.0.3 release with this fix :)

**Comment by gregorynicholas** [comment]
yep, thank you for contributing the fix.  i'll get a new release out later today.

**Comment by asottile** [comment]
Friendly reminder :)

**Comment by asottile** [comment]
@gregorynicholas friendly reminder :)

**Comment by asottile** [comment]
Thanks! 🎉

**Comment by asottile** [comment]
oh err uh, I celebrated too soon -- I saw the version bump but it didn't make it to pypi :(

**Pull request merged**
